from collections.abc import Iterable
from dataclasses import dataclass
from typing import Any, Protocol

from swarm_lens.core.models import Branch, Comment, Event, Fact, Run, State


@dataclass(frozen=True)
class RunContents:
    """One consistent read of a run: its branches, each branch's own events, and every comment written in it."""
    run: Run
    branches: list[Branch]
    own_events: dict[str, list[Event]]
    comments: list[Comment]


class HistoryStore(Protocol):
    def create_run(self, run: Run, branch: Branch) -> None: ...
    def runs(self) -> list[Run]: ...
    def run(self, run_id: str) -> Run: ...
    def branch(self, branch_id: str) -> Branch: ...
    def branches(self, run_id: str) -> list[Branch]: ...
    def fork(self, branch: Branch) -> None: ...
    def events(self, branch_id: str, cursor: int | None = None, after: int = 0) -> list[Event]: ...
    def append(self, branch_id: str, events: list[Event], expected_head: int) -> None: ...
    def save_snapshot(self, state: State) -> None: ...
    def snapshot(self, branch_id: str, cursor: int) -> State | None: ...
    def save_analysis(self, record: dict[str, Any]) -> None: ...
    def analyses(self, branch_id: str, cursor: int) -> list[dict[str, Any]]: ...
    def add_comment(self, comment: Comment) -> None: ...
    def comment(self, comment_id: str) -> Comment: ...
    def comments(self, branch_id: str) -> list[Comment]:
        """Own comments plus ancestors' comments up to each fork, ordered by position then creation time."""
    def update_comment(self, comment: Comment) -> None: ...
    def delete_comment(self, comment_id: str) -> None:
        """Delete a comment and, for a thread's top-level comment, all of its replies."""
    def run_contents(self, run_id: str) -> RunContents:
        """Read a whole run inside one read transaction, so concurrent writes cannot split it."""
    def import_run(self, run: Run, branches: list[Branch], batches: Iterable[tuple[list[Event], State]],
                   comments: list[Comment]) -> None:
        """Write a whole run in one transaction; any failure, including one raised by `batches`, leaves nothing.

        Branches come parents first and threads before their replies. Each batch is a branch's next events and
        the state after them; persist that snapshot before reading the next batch, because the state is reused.
        """


class Source(Protocol):
    """An application implements the meaning and ordering of its source records."""

    def facts(self) -> Iterable[Fact]: ...


class Runtime(Protocol):
    id: str

    def capabilities(self) -> dict[str, Any]: ...
    def continue_from(self, state: State, steps: int) -> Iterable[Fact]: ...


class VersionStore(Protocol):
    def checkpoint(self, run: Run, branch: Branch, state: State,
                   events: list[Event], message: str) -> str: ...


class Jobs(Protocol):
    """Durable job records of one plugin: queued, then claimed by one worker, then finished or failed."""

    def create(self, record: dict[str, Any]) -> None: ...
    def get(self, job_id: str) -> dict[str, Any]: ...
    def list(self, branch_id: str) -> list[dict[str, Any]]: ...
    def update(self, record: dict[str, Any]) -> None: ...
    def claim(self, job_id: str) -> dict[str, Any] | None: ...
    def recover_interrupted(self) -> None: ...
