from collections.abc import Iterable
from typing import Any, Protocol

from swarm_lens.core.models import Branch, Event, Fact, Run, State


class HistoryStore(Protocol):
    def create_run(self, run: Run, branch: Branch) -> None: ...
    def runs(self) -> list[Run]: ...
    def run(self, run_id: str) -> Run: ...
    def branch(self, branch_id: str) -> Branch: ...
    def branches(self, run_id: str) -> list[Branch]: ...
    def fork(self, branch: Branch) -> None: ...
    def events(self, branch_id: str, cursor: int | None = None, after: int = 0) -> list[Event]: ...
    def append(self, branch_id: str, events: list[Event], expected_head: int) -> None: ...
    def save_snapshot(self, state: State) -> None: ...
    def snapshot(self, branch_id: str, cursor: int) -> State | None: ...
    def save_analysis(self, record: dict[str, Any]) -> None: ...
    def analyses(self, branch_id: str, cursor: int) -> list[dict[str, Any]]: ...


class Source(Protocol):
    """An application implements the meaning and ordering of its source records."""

    def facts(self) -> Iterable[Fact]: ...


class Runtime(Protocol):
    id: str

    def capabilities(self) -> dict[str, Any]: ...
    def continue_from(self, state: State, steps: int) -> Iterable[Fact]: ...


class VersionStore(Protocol):
    def checkpoint(self, run: Run, branch: Branch, state: State,
                   events: list[Event], message: str) -> str: ...


class Plugin(Protocol):
    id: str
    version: str

    def run(self, context: Any, config: dict[str, Any]) -> dict[str, Any]: ...
